version: "3.7"
services:
  mysql:
    image: mysql:5.7
    environment:
      - 'MYSQL_DATABASE=challenge_app'
      - 'MYSQL_ROOT_PASSWORD=changeme'
      - 'MYSQL_USER=challenge_app_user'
      - 'MYSQL_PASSWORD=changeme'
    ports:
      - '3306:3306'
    networks:
      challenge_network:
  app:
    image: openjdk:17-jdk-alpine
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
    working_dir: /app
    command: ./mvnw spring-boot:run -Dspring-boot.run.profiles=dev
    depends_on:
      - mysql
    environment:
      - 'DB_HOST=mysql'
      - 'DB_DATABASE=challenge_app'
      - 'DB_USERNAME=challenge_app_user'
      - 'DB_PASSWORD=changeme'
      - "DB_PORT=3306"
    networks:
      challenge_network:
networks:
  challenge_network:

